# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Validador de json2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnValidar = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.validar())
        self.btnValidar.setGeometry(QtCore.QRect(670, 480, 75, 61))
        self.btnValidar.setObjectName("btnValidar")
        self.lblresultado = QtWidgets.QLabel(self.centralwidget)
        self.lblresultado.setGeometry(QtCore.QRect(460, 220, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblresultado.setFont(font)
        self.lblresultado.setObjectName("lblresultado")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(70, 60, 341, 421))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def validar(self):
        texto = str(self.plainTextEdit.toPlainText())
        
        try:
            json.loads(texto)
        except ValueError as err:
            flag=False
        else:
            flag= True
        
        if flag:
            self.lblresultado.setText("JSON válido")
        else:
            self.lblresultado.setText("JSON inválido")
            
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnValidar.setText(_translate("MainWindow", "Validar"))
        self.lblresultado.setText(_translate("MainWindow", "É um Json :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
